#!/usr/bin/env python3
"""Pre-render fixed strings to 8-bit coverage bitmaps for M5GFX.

The splash and loader show a small, fixed set of words. Rendering them at build
time instead of loading a font at run time keeps the exact Montserrat letterforms
and the exact letter spacing, costs less flash than the whole font, and avoids
swapping fonts mid-frame on a sprite that can only hold one at a time.

Coverage is 8-bit so the anti-aliasing survives; the renderer blends it against
whatever background it is drawn over, which is how the fade is done.

  python3 tools/prerender_text.py Montserrat-Medium.ttf \
      --out firmware/camera_stream/text_bitmaps.h
"""
import argparse
from PIL import Image, ImageFont

# name, text, pixel size, letter spacing. The tracking is part of the look.
STRINGS = [
    ("HackerDojo",  "HACKER DOJO",                   24, 3),
    ("Location",    "MOUNTAIN VIEW  /  SINCE 2009",  12, 1),
    ("Eyebrow",     "STANBOT  /  STACKCHAN",         12, 1),
    ("WakingUp",    "WAKING UP",                     24, 2),
    ("Joining",     "JOINING",                       24, 2),
    ("Connected",   "CONNECTED",                     24, 2),
    ("UsbOnly",     "USB ONLY",                      24, 2),
    ("NoNetwork",   "NO NETWORK",                    24, 2),
]


def render(ttf, text, size, tracking):
    font = ImageFont.truetype(ttf, size)
    ascent, _ = font.getmetrics()
    placed = []
    pen = 0
    for char in text:
        try:
            mask, offset = font.getmask2(char, mode="L")
        except (ValueError, OSError):
            mask, offset = None, (0, 0)
        if mask is not None and mask.size[0] and mask.size[1]:
            placed.append((Image.frombytes("L", mask.size, bytes(mask)),
                           pen + offset[0], offset[1]))
        pen += round(font.getlength(char)) + tracking
    width = max(1, pen - tracking)
    height = max(1, max((y + img.size[1] for img, _, y in placed), default=size))
    canvas = Image.new("L", (width, height), 0)
    for img, x, y in placed:
        canvas.paste(img, (x, y), img)
    return canvas, ascent


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("ttf")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    lines = ["#pragma once", "#include <cstdint>", "",
             "// Pre-rendered text, generated by tools/prerender_text.py from",
             f"// {args.ttf}. Montserrat Medium is the same face LVGL generates its",
             "// built-in fonts from, so these are the HID fixture's letterforms, not a",
             "// lookalike. SIL Open Font License 1.1; see docs/licenses.md.",
             "// Do not hand-edit: regenerate with the tool.", "",
             "namespace stanbot {", "",
             "struct TextBitmap {",
             "    const uint8_t* coverage;  // 8-bit alpha, row major",
             "    int16_t width;",
             "    int16_t height;",
             "    int16_t baseline;         // rows from the top down to the baseline",
             "};", ""]
    total = 0
    for name, text, size, tracking in STRINGS:
        image, ascent = render(args.ttf, text, size, tracking)
        data = image.tobytes()
        total += len(data)
        lines.append(f"// \"{text}\" at {size}px, tracking {tracking}")
        lines.append(f"alignas(4) inline constexpr uint8_t k{name}Pixels[] = {{")
        for index in range(0, len(data), 20):
            lines.append("    " + ", ".join(str(b) for b in data[index:index + 20]) + ",")
        lines.append("};")
        lines.append(f"inline constexpr TextBitmap k{name} = {{k{name}Pixels, "
                     f"{image.size[0]}, {image.size[1]}, {ascent}}};")
        lines.append("")
        print(f"{name}: {image.size[0]}x{image.size[1]}, {len(data)} bytes")
    lines += ["}  // namespace stanbot", ""]
    with open(args.out, "w") as handle:
        handle.write("\n".join(lines))
    print(f"total {total} bytes -> {args.out}")


if __name__ == "__main__":
    main()
