#!/usr/bin/env python3
"""Convert a TrueType face into a VLW font M5GFX can load from flash.

Why VLW and not the usual Adafruit GFX format: GFX fonts are one bit per pixel,
and the Hacker Dojo wordmark we are matching is anti-aliased. VLW carries eight
bits of coverage per pixel, so the result matches what LVGL renders on the HID
fixture instead of a jagged approximation of it.

The source face is Montserrat Medium, the same file LVGL generates its built-in
`lv_font_montserrat_*` fonts from, so the letterforms are not merely similar.

  python3 tools/ttf_to_vlw.py Montserrat-Medium.ttf 24 --name montserrat24 \
      --out firmware/camera_stream/font_montserrat24.h

Format, as read by LovyanGFX's VLWfont::loadFont, all big-endian uint32:
  header  gCount, version, fontSize, 0, ascent, descent
  glyphs  gCount x (unicode, height, width, xAdvance, dY, dX, reserved)
  bitmaps concatenated, width*height bytes of coverage, glyph-table order
"""
import argparse
import struct
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126  # printable ASCII is plenty for these screens


def build(ttf_path, size):
    font = ImageFont.truetype(ttf_path, size)
    ascent, descent = font.getmetrics()
    glyphs = []
    bitmaps = []
    for code in range(FIRST, LAST + 1):
        char = chr(code)
        advance = round(font.getlength(char))
        try:
            mask, offset = font.getmask2(char, mode="L")
        except (ValueError, OSError):
            mask, offset = None, (0, 0)
        if mask is None or mask.size[0] == 0 or mask.size[1] == 0:
            glyphs.append((code, 0, 0, advance, 0, 0))
            bitmaps.append(b"")
            continue
        width, height = mask.size
        coverage = bytes(Image.frombytes("L", mask.size, bytes(mask)).tobytes())
        # dY is the glyph top measured up from the baseline; PIL reports the
        # offset down from the top of the line, and the baseline sits at ascent.
        glyphs.append((code, height, width, advance, ascent - offset[1], offset[0]))
        bitmaps.append(coverage)
    return ascent, descent, glyphs, bitmaps


def encode(size, ascent, descent, glyphs, bitmaps):
    out = bytearray()
    out += struct.pack(">6I", len(glyphs), 11, size, 0, ascent, descent)
    for code, height, width, advance, dy, dx in glyphs:
        # dY and dX are signed on the wire; mask so struct accepts them.
        out += struct.pack(">7I", code, height, width, advance,
                           dy & 0xFFFFFFFF, dx & 0xFFFFFFFF, 0)
    for data in bitmaps:
        out += data
    return bytes(out)


def emit_header(blob, name, path, source):
    lines = [
        "#pragma once",
        "#include <cstdint>",
        "",
        f"// {name}: VLW font generated by tools/ttf_to_vlw.py from {source}.",
        "// Montserrat is licensed under the SIL Open Font License 1.1; see",
        "// docs/licenses.md. Do not hand-edit: regenerate with the tool.",
        f"// {len(blob)} bytes.",
        f"alignas(4) inline constexpr uint8_t {name}[] = {{",
    ]
    for index in range(0, len(blob), 16):
        chunk = ", ".join(f"0x{byte:02x}" for byte in blob[index:index + 16])
        lines.append(f"    {chunk},")
    lines += ["};", ""]
    with open(path, "w") as handle:
        handle.write("\n".join(lines))


def preview(ttf_path, size, text, path):
    """Render with PIL for a side-by-side eyeball check of the source face."""
    font = ImageFont.truetype(ttf_path, size)
    image = Image.new("RGB", (460, size * 2 + 20), (8, 12, 16))
    draw = ImageDraw.Draw(image)
    draw.text((10, 10), text, font=font, fill=(255, 255, 255))
    image.save(path)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("ttf")
    parser.add_argument("size", type=int)
    parser.add_argument("--name", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--preview")
    args = parser.parse_args()
    ascent, descent, glyphs, bitmaps = build(args.ttf, args.size)
    blob = encode(args.size, ascent, descent, glyphs, bitmaps)
    emit_header(blob, args.name, args.out, f"{args.ttf} at {args.size}px")
    if args.preview:
        preview(args.ttf, args.size, "HACKER DOJO", args.preview)
    print(f"{args.name}: {len(glyphs)} glyphs, ascent {ascent}, descent {descent}, "
          f"{len(blob)} bytes -> {args.out}")


if __name__ == "__main__":
    main()
