#!/bin/zsh
# Compile camera_stream with its git identity baked in, so the V command can
# say exactly what is on the robot.
#
#   firmware/build.sh
#
# Writes build_info.h next to the sketch, compiles, and deletes the header
# again whether or not the compile succeeds. A later compile that bypasses this
# script therefore reports commit "unknown" instead of inheriting a stale
# identity. The exported binaries land in firmware/camera_stream/build/, with a
# build_info.json beside them recording what they were built from.
#
# "dirty" covers everything under firmware/, submodules and untracked files
# included. Commit before building anything that will be flashed: a dirty
# build is exactly the kind the app warns about.
set -euo pipefail

repo=${0:A:h:h}
sketch=camera_stream
sketch_dir="$repo/firmware/$sketch"
fqbn='esp32:esp32:m5stack_cores3:PSRAM=enabled,USBMode=hwcdc,CDCOnBoot=cdc'
out_dir="$sketch_dir/build/esp32.esp32.m5stack_cores3"
cd "$repo"

commit=$(git rev-parse --short=12 HEAD)
if [[ -n "$(git status --porcelain -- firmware)" ]]; then dirty=true; else dirty=false; fi
built=$(date -u +%Y-%m-%dT%H:%M:%SZ)

info="$sketch_dir/build_info.h"
trap 'rm -f "$info"' EXIT
cat > "$info" <<HEADER
// Generated by firmware/build.sh. Do not commit; deleted after each compile.
#pragma once
#define STANBOT_GIT_COMMIT "$commit"
#define STANBOT_GIT_DIRTY "$dirty"
#define STANBOT_BUILD_TIME "$built"
HEADER

# Remove old exports first, so a failed compile cannot leave a previous
# binary sitting where the flash step expects this one.
rm -rf "$out_dir"
arduino-cli compile --fqbn "$fqbn" --libraries firmware/lib --export-binaries "$sketch_dir"

bin="$out_dir/$sketch.ino.bin"
sha=$(shasum -a 256 "$bin" | cut -d' ' -f1)
bytes=$(stat -f %z "$bin")
cat > "$out_dir/build_info.json" <<JSON
{"sketch":"$sketch","commit":"$commit","dirty":$dirty,"built":"$built","app_bin":"$sketch.ino.bin","app_bytes":$bytes,"app_sha256":"$sha"}
JSON
cat "$out_dir/build_info.json"
if [[ $dirty == true ]]; then
  echo "warning: built from uncommitted changes under firmware/; the robot will report dirty:true" >&2
fi
